service: openai-serverless

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, "prod"}
  region: ${opt:region, env:AWS_REGION, "us-west-2"}
  profile: ${env:AWS_PROFILE, "x-tech"}
  lambdaHashingVersion: 20201221
  memorySize: 256
  timeout: 30

variablesResolutionMode: 20210326
useDotenv: true

package:
  individually: false

functions:
  - ${file(./resources/authorizer_function.yml)}
  - ${file(./resources/openai_functions.yml)}

custom:
  prefix: ${self:service}-${self:provider.stage}

  pythonRequirements:
    dockerizePip: non-linux
    usePoetry: true
    zip: true

plugins:
  - serverless-python-requirements
  - serverless-offline
