stack:
  StackName: ${self:custom.prefix}-dynamodb
  Resources:
    UsageTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.prefix}-usage
        AttributeDefinitions:
          - AttributeName: uid
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: uid
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
  Outputs:
    UsageTableName:
      Value:
        Ref: UsageTable
      Export:
        Name: ${self:custom.prefix}-usage-table-name
